"""
Django settings for social_network project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os 
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wn#522qd@$d_76vpbmnf(b7wd#k55%nug1^g$1_a6=u(pa9^nt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]

AUTHENTICATION_BACKENDS = ( 
    'django.contrib.auth.backends.AllowAllUsersModelBackend', 
    'rest_framework.authentication.TokenAuthentication',
    'rest_framework.authentication.BasicAuthentication',
    'rest_framework.authentication.SessionAuthentication',    
    'account.backends.EmailBackend',    # custom class for email login

    'social_core.backends.open_id.OpenIdAuth',  # social auth
    'social_core.backends.google.GoogleOAuth2', # social auth
    'social_core.backends.google.GoogleOAuth',  # social auth
)

# Application definition

INSTALLED_APPS = [
    'chat.apps.ChatConfig',
    'account.apps.AccountConfig', 
    'friend.apps.FriendConfig',
    'api.apps.ApiConfig',
    'game.apps.GameConfig',
    
    'bootstrap4',
    'crispy_bootstrap4',
    'crispy_forms',
    'channels',
    'social_django',
    'rest_framework',
    'rest_framework_swagger',
    'corsheaders',
    'debug_toolbar',
    'django_extensions',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

    "debug_toolbar.middleware.DebugToolbarMiddleware",

    'social_django.middleware.SocialAuthExceptionMiddleware',
    'social_network.middleware.ActiveUserMiddleware',
    'social_network.middleware.RestrictConfidentialPageMiddleware',

]

# Configurations for debug_toolbar
INTERNAL_IPS = [
    "127.0.0.1",    
]

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': 'social_network.views.show_toolbar',   # restrict visibility of debug_toolbar
}


if DEBUG:                                                      
    import mimetypes                                                   
    mimetypes.add_type("application/javascript", ".js")


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'api.permissions.IsSuperUser'   # custom permissions for API endpoints
    ],
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4' # default styling dependency for crispy_forms

WSGI_APPLICATION = 'social_network.wsgi.application'
ASGI_APPLICATION = 'social_network.routing.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Set default relevant URLs 
ROOT_URLCONF = 'social_network.urls'
LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "/home"
LOGOUT_REDIRECT_URL = "/login"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


STATICFILES_DIRS = [ 
    os.path.join(BASE_DIR, 'static')
]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True


# Set up caching configurations and sessions 
CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
            'LOCATION': '127.0.0.1:11211',              
        }
    }

USER_ONLINE_TIMEOUT = 300 # Number of seconds of inactivity before a user is marked offline
USER_LASTSEEN_TIMEOUT = 60 * 60 * 24 * 7 # Time to track inactive users before last seen is removed from cache

SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Session expires once user closes their browser 
SESSION_COOKIE_AGE = 86400 # Set time out to be twenty-four hours
SESSION_SAVE_EVERY_REQUEST = True # Saves session to database and updates timeout for session expiry 

ACCOUNT_SIGNUP_FORM_CLASS = 'account.forms.'

# Set up Google oauth2 credentials for social-oauth
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '225323846404-f34c3lc2tb91t4t2dekc9lpfjngj7s5q.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

# # domain white list; currently do not need one
# SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = ['abc.com']

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/user.birthday.read',
    'https://www.googleapis.com/auth/userinfo.profile'
]

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',

    'social_core.pipeline.user.get_username',   
    'social_network.pipeline.associate_by_email',   # custom pipeline
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_network.pipeline.create_profile',  # custom pipeline
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details'
)


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-uk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# # detailed logging
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     },
# }